name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debug METRICS_TOKEN is set
        run: |
          if [ -z "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "METRICS_TOKEN is NOT set!"
            exit 1
          else
            echo "METRICS_TOKEN is set."
          fi
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kirigaya07
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
